# Generated by Django 3.2.5 on 2021-12-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Annual_Income', models.PositiveBigIntegerField(null=True)),
                ('Spending_score', models.PositiveIntegerField(null=True)),
                ('prediction', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
