# Generated by Django 3.2.5 on 2021-12-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20211223_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Annual_Income',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='prediction',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
